# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
#- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- powershell: .\Setup\Projects\Demo\import.ps1       
  workingDirectory: $(Build.Repository.LocalPath)\Setup\Projects\Demo
  env: 
    ConnectionString: $(connectionString)
    SolutionName: $(solutionName)
  
  