
trigger:
- master

pool:
  name: Hosted VS2017
  demands:
  - msbuild
  - visualstudio

variables:
  SolutionName: 'ContactManagement'

steps:
- task: PowerShell@2
  displayName: 'Replace solution code files'
  inputs:
    targetType: filePath
    filePath: ./PipelineScripts/replacefiles.ps1
    workingDirectory: PipelineScripts

- task: microsoft-IsvExpTools.PowerApps-BuildTools.powerapps-tool-installer.PowerAppsToolInstaller@0
  displayName: 'PowerApps Tool Installer '

- task: microsoft-IsvExpTools.PowerApps-BuildTools.powerapps-pack-solution.PowerAppsPackSolution@0
  displayName: 'PowerApps Pack Solution '
  inputs:
    SolutionSourceFolder: 'Solutions\$(SolutionName)'
    SolutionOutputFile: '$(Build.ArtifactStagingDirectory)\solutions\solution_managed.zip'
    SolutionType: Managed

- task: microsoft-IsvExpTools.PowerApps-BuildTools.powerapps-pack-solution.PowerAppsPackSolution@0
  displayName: 'PowerApps Pack Solution  (Unmanaged)'
  inputs:
    SolutionSourceFolder: 'Solutions\$(SolutionName)'
    SolutionOutputFile: '$(Build.ArtifactStagingDirectory)\solutions\solution.zip'

- task: microsoft-IsvExpTools.PowerApps-BuildTools.powerapps-import-solution.PowerAppsImportSolution@0
  displayName: 'PowerApps Import Solution '
  inputs:
    PowerAppsEnvironment: 'Smoke Test'
    SolutionInputFile: '$(Build.ArtifactStagingDirectory)\solutions\solution_managed.zip'
    ConvertToManaged: false
    HoldingSolution: false
    OverwriteUnmanagedCustomizations: false
    PublishWorkflows: false
    SkipProductUpdateDependencies: false

- task: VSBuild@1
  displayName: 'Build test solution'
  inputs:
    solution: 'Test\UIAutomation.sln'
    vsVersion: 15.0
    configuration: debug

- task: VisualStudioTestPlatformInstaller@1
  displayName: 'Visual Studio Test Platform Installer'

- task: VSTest@2
  displayName: 'Run the tests'
  inputs:
    testAssemblyVer2: |
     **\UIAutomation.dll
     !**\obj\**
    searchFolder: 'Test\UIAutomation\bin\Debug'
    testFiltercriteria: 'Name=UCIDevOpsCreateTag'
    uiTests: true
    runSettingsFile: Test/UIAutomation/test.runsettings
    overrideTestrunParameters: '-OnlineCrmUrl https://orgc0500748.crm3.dynamics.com -OnlineUsername easyrepro@treecatsoftware.com -OnlinePassword TestUser123_'

- task: PublishPipelineArtifact@1
  displayName: 'Publish Pipeline Artifact (solution_managed.zip)'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)\solutions\solution_managed.zip'
    artifact: 'solution_managed.zip'

- task: PublishPipelineArtifact@1
  displayName: 'Publish Pipeline Artifact (solution.zip) '
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)\solutions\solution.zip'
    artifact: solution.zip
