pool:
  name: Hosted VS2017
  demands:
  - msbuild
  - visualstudio

variables:
  SolutionName: 'ContactManagement'

steps:
- task: PowerShell@2
  displayName: 'Replace solution code files'
  inputs:
    targetType: filePath
    filePath: ./PipelineScripts/replacefiles.ps1
    workingDirectory: PipelineScripts

- task: microsoft-IsvExpTools.PowerApps-BuildTools.powerapps-tool-installer.PowerAppsToolInstaller@0
  displayName: 'PowerApps Tool Installer '

- task: microsoft-IsvExpTools.PowerApps-BuildTools.powerapps-pack-solution.PowerAppsPackSolution@0
  displayName: 'PowerApps Pack Solution  (Unmanaged)'
  inputs:
    SolutionSourceFolder: 'Solutions\$(SolutionName)'
    SolutionOutputFile: '$(Build.ArtifactStagingDirectory)\solutions\solution.zip'

- task: microsoft-IsvExpTools.PowerApps-BuildTools.powerapps-import-solution.PowerAppsImportSolution@0
  displayName: 'PowerApps Import Solution '
  inputs:
    PowerAppsEnvironment: 'Dev$(Build.SourceBranchName)'
    SolutionInputFile: '$(Build.ArtifactStagingDirectory)\solutions\solution.zip'
    ConvertToManaged: false
    HoldingSolution: false
    OverwriteUnmanagedCustomizations: false
    PublishWorkflows: false
    SkipProductUpdateDependencies: false